var editionIds = [
  "CS",
  "PTS",
  "G",
  "A",
  "B",
  "I",
  "C",
  "D",
  "E",
  "F",
  "H",
  "J",
  "K",
  "L",
];

var bibleEditions = [
  "CS",
  "PTS",
  "G",
  "A",
  "B",
  "I",
  "C",
  "D",
  "E",
  "F",
  "H",
  "J",
  "K",
  "L",
];

var verses = "Nigamana";

var bibleVerses = [
  [
    "abhidhammāvatāro yaṃ varo paramagambhīro icchatā nipuṇaṃ buddhiṃ bhikkhunā pana sotabbo",
    "abhidhammāvatāro yan varo paramagambhīro icchatā nipuṇaṃ buddhiṃ bhikkhunā pana sotabbo",
    "abhidhammāvatāro yaṃ varo paramagambhīro icchatā nipuṇaṃ buddhiṃ sotabbo bhikkhunā pana",
    "abhidhammāvatāro yaṃ varo paramagambhīro icchatā nipuṇaṃ buddhiṃ bhikkhunā pana sotabbo",
    "abhidhammāvatāro yaṃ varo paramagambhīro icchetā nipuṇaṃ buddhiṃ bhikkhunā pana sotabbo",
    "abhidhammāvatāro yaṃ varo paramagambhīro icchatā nipuṇaṃ buddhim bhikkhunā pana sotabbo",
    "abhidhammāvatāro yaṃ varo paramagambhīro icchatānaṃ puṇaṃ buddhim bhibhikkhunā pana sotabbo",
    "abhidhammāvatāro yaṃ varo paramagantiro icchatā nipuṇaṃ buddhiṃ bhikkhunā pana sotabbo",
    "abhidhammāvatāro yaṃ varo paramagambhīro iccavatā nipuṇa buddhi bhikkhunā pana sotabbo",
    "abhidhammāvatāro yaṃ varo paramagambhīro icchatā nipuṇa buddhitāni bhikkhunā pana sotabbo",
    "abhidhammāvatāro yaṃ varo paramagambhīro icchatā nipuṇaṃ buddhiṃ bhikkhunā pana sotabbo",
    "abhidhammāvatāro yaṃ varo paramagambhīro icchatā nipuṇaṃ vuddhi bhikkhunā ma sokabbo",
    "abhidhammāvatāro yaṃ varo paramagambhīro icchatā nipuṇa buddhi bhikkhunā pana sotabbo",
    "abhidhammāvatāro yaṃ varo paramagambhīro icchatā nipuṇa buddhi bhikkhunā pana sotabbo",
  ],
  [
    "sumatimativicārabodhano vimativimohavināsano ayaṃ kumatimatimahātamonāso paṭumatibhāsakaro mato mayā",
    "sumatimativicārabodhano vimativimohavināsano ayaṃ kumatimatimahātamoharo paṭumatihāsakaro mato mayā",
    "sumatimativicārabodhano vimatimativināsano ayaṃ kumatimatimahātamoharā paṭumatisakaro kato mayā",
    "sumatimativicārabodhano vimativimohavināsano ayaṃ kumatimatimahātamonāso paṭumatibhāsakakaro mayā",
    "sumatimaticārabodhano vimativimohavināsano ayaṃ kumatimatimahātamonāso paṭumatibhāsakaro mato mayā",
    "sumatimativicārabodhano vimativimohavināsano ayaṃ kumatimatimahātamosāno paṭumatigāmakaro mato mayā",
    "sumatimaticārabodhano vimativimohavināsano ayaṃ kumatimatimahātasāno paṭumatigāmakaro mato mayā",
    "sumatimativicārabodhano vimativimohavināsano sahaṃ kumatimatimahātamohāro paṭumatibhāsakaro mato mayā",
    "sumatimativicārabodhano vimativimohavināsano ayaṃ kumatimatimahātamonāso paṭumatibhāsakaro mato mayā",
    "sumatimativitarabodhano vimativimohavināsano ayaṃ kumatimatimahātamohāro paṭumatibhāsakaro mato mayā",
    "sumatimativicārabodhano vimativimohavināsano ayaṃ kumatimatimahātamonāso paṭumatibhāsakaro mato mayā",
    "sumatimaticārabodhano vimativimohavināsano ayaṃ kumatimatimahātamo sādhanā padhumatigāmakaro mato mayā",
    "sumatimativicārabodhano vimatimativināsano ayaṃ kumatimatimahātamoharo paṭumatibhāsakaro mato mayā",
    "sumatimativicārabodhano vimativimohavināsano ayaṃ kumatimatimahātamoharesāva paṭumatibhāsakaro mato mayā",
  ],
  [
    "yato sumatinā mato nāmato āyācitasammānato mānato tato hi racito sadā tosadā mayā hitavibhāvanā bhāvanā",
    "yato sumatinā mato nāmato āyācitasamānato mānato tato viracito padāto padā mayā hitavibhāvanā bhāvanā",
    "yato sumatinā mato āyācittasamānato mānato tato hi ricito va dātovadā mayā hitavibhāvanā bhāvanā",
    "yato sumatinā mato nāmato āyācitasamānato mānato tato hi carito padāto padā mayā hitavibhāvanā bhāvanā",
    "yato sumati nāmako nāmato āyācitasamānito mānato tato hi racito padato padā mayā hitavibhāvinā",
    "yato sumati nāmako āyācitamānato tato hi ravito padato padā mayā hitavibhāvinā bhāvanā",
    "yato sumati nāmako āyācitasamānato mānaso kato hi rapito padato padā mayā hitavibhāvinā bhāvanā",
    "yato sumatinā mato nāmato āyācitasamānato mānato tato hi racito sadāto sadāto mayā hitavibhāvanā bhāvanā",
    "yato sumati nāmako nāmako āyācitasamānato mānato tato hi racito sadā tosadā mayā hitavibhāvanā bhāvanā",
    "yato sumatinā mato nāmato āyācitasamānato mānato tato hi racito ca sadāto sadāto mayā hitavibhāvanā bhāvanā",
    "yato sumatinā mato nāmato āyācitasamānato mānato tato hi racito sadato sadā mayā hitavibhāvanā bhāvanā",
    "yato sumati nāmako āyācitamānato tato hi racito padato padā mayā hititāvibhāvanā",
    "yato sumatinā mato āyācitasamānato tato hi racito sadāto sadāto mayā hitavibhāvanā bhāvanā",
    "yato sumatinā mato āyācitasamānato mānato tato hi racito saddāto sadā mayā hitabhāvanā bhāvanā",
  ],
  [
    "atthato ganthato cāpi yuttito cāpi ettha ca ayuttaṃ vā viruddhaṃ vā yadi dissati kiñci pi",
    "atthato ganthato vāpi yuttito vāpi ettha ca ayuttaṃ vā viruddhaṃ vā yadi dissati kiñci pi",
    "atthato ganthato cāpi yuttito cāpi ettha ca ayuttaṃ vā viruddhaṃ vā yadi dissati kiñci pi",
    "atthato ganthato cāpi yuttito cāpi ettha ca ayuttaṃ vā viruddhaṃ vā yadi dissati kiñci pi",
    "atthato gandhato cāpi yuttito vāpi ettha ca ayuttaṃ vā viruddhaṃ vā yadi dissati kiñcāpi",
    "matthato gandhato cāpi yuttito vāpi ettha ca ayuttaṃ vā viruddhaṃ vā yadi dissati kiñci pi",
    "matthato gandhato cāpi yuttito vāpi ettha ca ayuttaṃ vā visuddhaṃ vā yadi dissati kiñci pi",
    "atthato gandhato yuttito vāpi ettha ca ayuttaṃ vā viruddhaṃ vā yadi dissati kiñci pi",
    "atthato gandhato cāpi yuttito vāpi ettha ca ayuttaṃ vā viruddhaṃ vā yadi dissati kiñci pi",
    "atthato ganthato cāpi yuttito vāpi ettha ca ayuttaṃ vā viruddhaṃ vā yadi dissati kiñci pi",
    "atthato ganthato vāpi yuttito vāpi ettha ca ayuttaṃ vā viruddhaṃ vā yadi dissati kiñci pi",
    "matthako gandhato cāpi yuttito cāpi ettha ca ayuttaṃ vā viruddhaṃ vā yadi dissati kiñci pi",
    "atthato gantuto vāpi yuttito vāpi ettha ca ayutta vā viruddha vā yadi dissati kiñci pi",
    "atthato gantuto vāpi yuttito vāpi ettha ca ayuttaṃ vā viruddhaṃ vā yadi dissati kiñci pi",
  ],
  [
    "pubbāparaṃ viloketvā vicāretvā punappunaṃ dhīmatā saṅgahetabbaṃ gahetabbaṃ na dosato",
    "pubbāparaṃ viloketvā vicāretvā punappunaṃ dhīmatā taṃ gahetabbaṃ gahetabbaṃ na dosato",
    "pubbāparaṃ viloketvā vicāretvā punappunaṃ dhīmatā taṃ gahetabbaṃ gahetabbaṃ na dosato",
    "pubbāparaṃ viloketvā vicāretvā punappunaṃ dhīmatā saṅgahetabbaṃ gahetabbaṃ na dosato",
    "pubbāparaṃ viloketvā vicāretvā punappunaṃ dhīmatā saṅgahetabbaṃ gahetabbaṃ nidosato",
    "pubbāparaṃ viloketvā vicāritvā punappunaṃ dhīmatā saṅgahetabbaṃ gahetabban na dosa<e?>to",
    "pubbāparaṃ viloketvā gicāritvā punappunaṃ dhīmatā saṃgayetatabbaṃ gahetabban na dosako",
    "pubbāparaṃ viloketvā vicāretvā punappunaṃ dhīmatā taṃ gahetabbaṃ gahetabbaṃ na dosato",
    "pubbāparaṃ viloketvā vicāretvā punappunaṃ dhīmatā saṅgahetabbaṃ gahetabbaṃ na dosato",
    "pubbāparaṃ viloketvā vicāretvā punappunaṃ dhīmatā taṃ gahetabbaṃ gahetabbaṃ na dosato",
    "pubbāparaṃ viloketvā vicāretvā punappunaṃ dhīmatā taṃ gahetabbaṃ gahetabbaṃ na dosato",
    "pubbāparaṃ viloketvā vicāritvā punappunaṃ dhimatā saṃgahetabbaṃ gahetabban dha dosato",
    "pubbāparaṃ viloketvā vicāretvā punappunaṃ vimatā taṃ gahetabbaṃ gahetabbaṃ na dosato",
    "pubbāparaṃ viloketvā vicāretvā punappunaṃ dhīmatā saṃgahetabbaṃ gahetabbaṃ na dosato",
  ],
  [
    "tividhā byappathānañhi gatiyo dubbidhāpi ce tasmā upaparikkhitvā veditabbaṃ vibhāvinā",
    "tividhā vyavadhānanaṃ gatiyo dullabhāpi ca tasmā upaparikkhitvā veditabbaṃ vibhāvinā",
    "tividhā byāpathānaṃ hi gatiyo dubbudhāpi ca tasmā upaparikkhitvā veditabbā vibhāvinā",
    "tividhā byappathānañhi gatiyo dubbidhāpi ce tasmā upaparikkhitvā veditabbaṃ vibhāvinā",
    "tividhā byapadanaññi gatiyo dubbidhāpe ce tasmā upaparikkhitvā veditabbaṃ vibhāvinā",
    "tividhā byāsadhānañhi satiyo dubbidhāpi ce tasmā upaparikkhitvā veditabbaṃ vibhāvinā",
    "tividhā byāsadhānañhi satiyo dubbidhāpi ce tasmā upaparikkhitvā veditabbaṃ vibhāvinā",
    "tividhā byavadhānaṃhi gatiyo dullabhāpi ca tasmā upaparikkhitvā veditabbaṃ vibhāvinā",
    "tividhā byappathānañhi gatiyo dubbidhāpe ce tasmā upaparikkhitvā veditabbaṃ vibhāvinā",
    "tividhā byavadhānaṃhi gatiyo du(ac bba)llabhāpi ca tasmā upaparikkhitvā veditabbaṃ vibhāvinā",
    "tividhā byappathānañhi gatiyo dubbidhāpi ce tasmā upaparikkhitvā veditabbaṃ vibhāvinā",
    "tividhā byāsadhānañhi satiyo dubbidhāpi ce tasmā upaparikkhitvā veditabbaṃ vibhāvinā",
    "tividhā byavadhānaṃhi gatiyo dullabhāpi ca tasmā uparikkhitvā veditabbaṃ vibhāvinā",
    "tividhā byapadhānaṃhi gatiyo dubbidhāpe ca tasmā upaparikkhitvā veditabbaṃ bhāvinā",
  ],
  [
    "nikāyantaraladdhīhi asammisso anākulo mahāvihāravāsīnaṃ vācanāmagganissito",
    "nikāyantaraladdhīhi asammisso anākulo mahāvihāravāsīnaṃ vācanāmagganissito",
    "nikāyantaraladdhīhi asammisso anākulo mahāvihāravāsīnaṃ vācanāmagganissito",
    "nikāyantaraladdhīhi asammisso anākulo mahāvihāravāsīnaṃ vācanāmagganissito",
    "nikāyantaraladdhiṃ hi asammisso anākulo mahāvihāravāsinaṃ vācanāmaggam anissito",
    "nikāyantaraladdhihi asammisso anākulo mahāvihāravāsīnaṃ vācanāmagganissito",
    "nikāyantaraladdhīhi amiso anākulo mahāvihāravāsīnaṃ vācanāmagganissito",
    "nikāyanturaladdhīhi asammisso anākulo mahāvihāravāsīnaṃ vācanāmagganissito",
    "nikāyantaraladdhīhi asammisso anākulo mahāvihāravāsīnaṃ vācanāmagganissito",
    "nikāyantaraladdhīhi asammisso anākulo mahāvihāravāsīnaṃ vācanāmagganissito",
    "nikāyantaraladdhīhi asammisso anākulo mahāvihāravāsīnaṃ vācanāmagganissito",
    "nikārantaraladdhīhi asammisso anākulo mahāvihāravāsīnaṃ vācanāmagganissito",
    "nikāyantaraladdhihi āsammasso anākulo mahāvihāravāsinaṃ vācanāmagganissito",
    "nikāyantaraladdhihi āsammisso anākulo mahāvihāravāsīnaṃ bhāvanāmagginissito",
  ],
  [
    "madhurakkharasaṃyutto attho yasmā pakāsito tasmā hitatthakāmena kātabbo ettha ādaro",
    "madhurakkharasaṃyutto attho yasmā pakāsito tasmā hitatthakāmena kātabbo ettha ādaro",
    "madurakkharasaṃyutto attho yasmā pakāsito tasmā hitatthakāmena kātabbo ettha sādaro",
    "madhurakkharasaṃyutto attho yasmā pakāsito tasmā hitatthakāmena kātabbo ettha ādaro",
    "madhurakkharasaṃyutto attho yasmā pakāsito tasmā hitatthakāmena kātabbo ettha āraddho",
    "madhurakkharasaṃyutto attho yasmā pakāsito tasmā hitatthakāmena kātabbo ettha araddho",
    "madhurakkharasaṃyutto attho yasmā pakāsito tasmā hitatthakāmena kātabbo ettha āraddho",
    "madhurakkharasaṃyutto attho yasmā pakāsito tasmā hitatthakāmena kātabbo ettha ādharo",
    "madhurakkharasaṃyutto attho yasmā pakāsito tasmā hitatthakāmena kātabbo ettha ādaro",
    "madhurakkharasaṃyutto attho yasmā pakāsito tasmā hitatthakāmena kātabbo ettha ādayo",
    "madhurakkharasaṃyutto attho yasmā pakāsito tasmā hitatthakāmena kātabbo ettha ādaro",
    "madhurakkharasaṃyutto attho yasmā pakāsito tasmā hitatthakāmena kātabbo etta āraddho",
    "madhurakkharasaṃmayutto attho yasmā pakāsito tasmā hitatthakāmena kātabbo ettha ādayo",
    "madhurakkharasaṃyutto attho yasmā pakāsito tasmā hitatthakāmena kātabbo ettha ādaro",
  ],
  [
    "saddhammaṭṭhitikāmena karontena ca yaṃ mayā puññam adhigataṃ tena sukhaṃ pappontu pāṇino",
    "saddhammaṭṭhitikāmena karontena ca yaṃ mayā puññam adhigataṃ tena sukhaṃ pappontu pāṇino",
    "saddhammaṭṭhitikāmena karontena ca yaṃ mayā puññaṃ adhigatan tena sukhaṃ pappontu ṭhāṇino",
    "saddhammaṭṭhitikāmena karontena ca yaṃ mayā puññam adhigatan tena sukhaṃ pappontu pāṇino",
    "saddhammaṭṭhitikāmena karontena ca yaṃ mayā puññam adhigatan tena sukhaṃ pappentu pāṇino",
    "saddhammaṭṭhitikāmena karontena ca yam makā puññam adhagatan tena sukham pappontu pāṇino",
    "saddhammaṭṭhitikāmena karontena ca yaṃ mayā puññam agadhatan tena sukhaṃ pappontu pāṇino",
    "saddhammaṭṭhitikāmena karontena ca yaṃ mayā puññam adhigan tene sukhaṃ pappontu pāṇino",
    "saddhammaṭṭhitikāmena karontena ca yam mayā puññam adhigatan(ac adhigataṃ) tena sukhaṃ pappontu pāṇino",
    "saddhammaṭṭhitikāmena karontena ca yaṃ mayā puññam adhigatan tena sukhaṃ pappontu pāṇino",
    "saddhammaṭṭhitikāmena karontena ca yaṃ mayā puññaṃ adhigatan tena sukhaṃ pappontu pāṇino",
    "saddhammaṭṭhitikāmena karontena ca sammatā puññam agetan tena sukham pappontu pāṇino",
    "saddhammaṭṭhitikāmena karontena ca yaṃ mayā paññam adhigatan tena sukhaṃ pamonta pāṇino",
    "saddhammaṭṭhitikāmena karontena ca yaṃ mayā puññam adhigatan tena sukhaṃ pamonti pāṇino",
  ],
  [
    "antarāyaṃ vinā cāyaṃ yathā siddhim upāgato tathā kalyāṇasaṅkappā siddhiṃ gacchantu pāṇinaṃ",
    "antarāyaṃ vinā cāyaṃ yathā siddhim upāgato tathā kalyāṇasaṅkappā siddhiṃ gacchantu pāṇinaṃ",
    "antarāyaṃ vinā cāyaṃ yathā siddhim upāgato tathā kalyāṇasaṅkappā siddhiṃ gacchantu pāṇino",
    "antarāyaṃ vinā cāyaṃ yathā siddhim upāgato tathā kalyāṇasaṅkappā siddhiṃ gacchantu pāṇinaṃ",
    "antarāyaṃ vinā cāyaṃ yathā siddhim upāgato tathā kalyāṇasaṅkappā siddhiṃ gacchantu pāṇinaṃ",
    "anantarāyaṃ vinā cāyaṃ yathā siddham upāgato tathā kalyāṇasaṃkappā siddhiṃ gacchantu pāṇinaṃ",
    "antarāyaṃ vinā cāyaṃ yathā siddham upāgato tato kalyāṇasaṃkappā siddhi gacchantu pāṇinaṃ",
    "antarāyaṃ vinā cāraṃ yathā saddhim upāgato tathā kalyāṇasaṃkappā siddhi gacchantu pāṇinaṃ",
    "antarāyaṃ vinā cāyaṃ yathā siddhim upāgato tathā kalyāṇasaṅkappā siddhiṃ gacchantu pāṇinaṃ",
    "antarāyaṃ vinā cāyaṃ yathā siddhim upāgato tathā kalyāṇasaṃkappā siddhiṃ gacchantu pāṇinaṃ",
    "antarāyaṃ vinā cāyaṃ yathā siddhim upāgato tathā kalyāṇasaṅkappā siddhaṃ gacchantu pāṇinaṃ",
    "anantarāyaṃ vinā cāyaṃ yathā siddham upāgato tathā kalyāṇasaṃkappā siddhi gacchantu pāṇinaṃ",
    "antarāyaṃ vi vāyaṃ yathā siddhim upāgato tathā kalyāṇasaṅkabbā siddhiṃ gacchantu pāṇinaṃ",
    "antarāyaṃ vinā cāyaṃ yathā siddhim upāgato tathā kalyāṇasaṅkappā siddhiṃ gacchantu pāṇinaṃ",
  ],
  [
    "naranārigaṇākiṇṇe asaṃkiṇṇakulākule phīte sabbaṅgasampanne supasannasitodake",
    "naranārigaṇākiṇṇe asaṃkiṇṇakulākule phīte sabbaṅgasampanne pasannasaritūdake",
    "naranārigaṇākiṇṇe asaṅkiṇṇakulākule phīte sabbaṅgasampanne sampannasarikūdake",
    "naranārigaṇākiṇṇe asaṃkiṇṇakulākule phīte sabbaṅgasampanne supasannasitodake",
    "naranārigaṇākiṇṇe asaṃkiṇṇe asaṃkiṇṇakūlākule pite sabbaṅgasampanne susampannasitodake",
    "naranārigaṇākiṇṇe asaṃkiṇṇakulākule phīte sabbaṅgasampanne sasannuparituraṇe",
    "naranārigaṇākiṇṇe asaṃkiṇṇakusalākule phīte sabbaṅgasampanne sasannaparituraṇe",
    "naranārigaṇākiṇṇe asaṃkiṇṇakulākule phīte sabbaṅgasampanne pasannasaritudake",
    "naranārigaṇākiṇṇe asaṃkiṇṇakulākule phīte sabbaṅgasampanne susampannasitodake",
    "naranārigaṇākiṇṇe asaṃkiṇṇakulākule bite sabbaṅgasampanne suppasannasaritudake",
    "naranārigaṇākiṇṇe asaṃkiṇṇakulākule phīte sabbaṅgasampanne susampannasitodake",
    "narānārigaṇātiṇṇe asaṃkiṇṇakulākule phīte sabbaṅgasampanne sasannasparituraṇe",
    "naranārigaṇākiṇṇe asaṃkiṇṇakulākule pite sabbaṅgasampane pasannāsaritudake",
    "naranārigaṇākiṇṇe asaṃkiṇṇakulākule phīte sabbaṅgasampanne supasannasitodake",
  ],
  [
    "nānāratanasampuṇṇe vividhāpaṇasaṅkaṭe kāverapaṭṭane ramme nānārāmopasobhite",
    "nānāratanasampuṇṇe vividhāpaṇasaṅkaṭe kāverapaṭṭane ramme nānārāmopasobhite",
    "nānāratanasampuṇṇe vividhāpaṇasaṅkaṭe kāverapaṭṭane ramme nānārāmopasābhite",
    "nānāratanasampuṇṇe vividhāpaṇasaṅkaṭe kāverapaṭṭane ramme nānārāmopasobhite",
    "nānāratanasampuṇṇe vividhāpaṇasaṅkaṭe kāverappaṭṭane ramme nānārammovasobhite",
    "nānāratanasampuṇṇe vividhāpaṇasaṅkaṭe kāverappaṭṭane ramme nānāgamopasobhite",
    "nānāratanasampuṇṇe vividhāpanasaṅkaṭe kāverappaṭṭane ramme nānāgāmopasobhite",
    "nānāratanasaṃpuṇṇe vividhāpanasaṃgate kāverapaṭṭane ramme nānārāmopasobhite",
    "nānāratanasampuṇṇe vividhāpaṇasaṅkate kāverapaṭṭane ramme nānārāmopasobhite",
    "nānāratanasampuṇṇe vividhāpanasaṃkaṭe kāverapaṭṭhame ramme nānāramopasobhite",
    "nānāratanasampuṇṇe vividhāpanasaṅkate kāverapaṭṭane ramme nānārāmopasobhite",
    "nānāratanasampuṇṇe vividhāpanasaṅkaṭe kāverappanne ramme nānāgādhopasobhite",
    "nānāratanasampuṇṇe vividhāpaṇasaṃkate kāverapaṭṭape ramme nānārāmopasobhite",
    "nānāratanasampuṇṇe vividhāpaṇasaṅkaṭe kāverapaṭṭane ramme nānārāmopasobhite",
  ],
  [
    "kelāsasikharākāra pāsādapaṭimaṇḍite kārite kaṇhadāsena dassanīye manorame",
    "kelāsasikharākāra pāsādapaṭimaṇḍite kārite kaṇhadāsena dassanīye manorame",
    "kelāsasikharākāra pāsādapaṭimaṇḍite kārite kaṇhadāsena dassanīye manorame",
    "kelāsasikharākāra pāsādapaṭimaṇḍite kārite kaṇḍadāsena dassanīye manorame",
    "kilāsasikharākāra pāsādapaṭimaṇḍite kārite kaṇḍanāmena dasānīye manorame",
    "kelāsasikharākāra pāsādapaṭimaṇḍite kārite kaṇḍadāpane dassaniye manorame",
    "kelāsasikharākāra pāsādapaṭimaṇḍite kārite kaṇḍadāpane dassanīye manorame",
    "kelāsasikharākāra pāsādapaṭimaṇḍite kārite kaṇhadāsena dassanīye manorame",
    "kelāsasikharākāra pāsādapaṭimaṇḍite kārite kaṇḍanāmena dassanīye manoramme",
    "kelāsasikharākāra pāsādapaṭimaṇḍite kārite kaṇhadāsena dassanīye manorame",
    "kelāsasikharākāra pāsādapaṭimaṇḍite kārite kaṇādāsena dassanīye manorame",
    "kelāsasiparākāra pāsādaparimaṇḍite kārite kaṇḍadāpane dassanīye manoramme",
    "kesāsasikharākāra pāsādapaṭipaṇḍite kārijā tataṇhadāsena dassanīye manorame",
    "kelāsasikharākāra pāsādapaṭimaṇḍite kārite kaṇhadāsena dassanīye manorame",
  ],
  [
    "vihāre vividhākāra cārupākāragopure tattha pācīnapāsāde mayā nivasatā sadā",
    "vihāre vividhākāra cārupākāragopure tattha pācīnapāsāde mayā nivasatā satā",
    "vihāre vividhākāra cārupākāragopure tattha pācīnapāsāde mayā nivasatā sadā",
    "vihāre vividhākāra cārupākāragopure tattha pācīnapāsāde mayā nivasatā sadā",
    "vihāre vividhākāra arūpākāragopūre tattha pācīnapāsāde mayā nivesatā sadā",
    "vihāre vividhākāra cārūpākāragopure tattha pācīnapāsāde mayā nivasata satā",
    "vihāre vividhakāra cārupikāragopūre tattha pācinapāsāde mayā nimasatā satā",
    "vihāre vividhākāra cārupākāragopure tattha pācīnapāsāde mayā nivasatā satā",
    "vihāre vividhākāra cārupākāragopūre tattha pācinapāsāde mayā nivasatā sadā",
    "vihāre vividhākāra cārupākāragopure tattha pācīnapāsāde mayā nivesatā satā",
    "vihāre vividhākāraṃ cārupākāragopure tattha pācinapāsāde mayā nivasatā sadā",
    "vihāre vividhākāra vārūpākāragopūre tattha pācīnapāsāde mayā niseva satā",
    "vihāre vidhākāra cāruvākāragopure tattha pāvīnapāsāde mayā nivesata satā",
    "vihāre vividhākāra cārupākāragopure tattha pācīnapāsāde mayā nivasatā sadā",
  ],
  [
    "asallekhamasākhalye sīlādiguṇasobhinā ayaṃ sumatinā sādhu yācitena kato satā",
    "rammasallekhasākhalya sīlādiguṇasobhinā ayaṃ sumatinā sādhu yācitena kato tato",
    "dam(p?)asallekkhasākhya liṇa diguṇasobhinā ayaṃ sumatinā sādhu yācitena kato satā",
    "asallekhamasākhalye sīlādiguṇasobhinā ayaṃ sumatinā sādhu yācitena kato satā",
    "asallekhamasālye sīlādiguṇasobhinā ayaṃ mutinā sādhu yācitena kato sadā",
    "asallekhamasākhalye sīlādiguṇa<?>esobhinā ayaṃ samutinā sādhu yācitena kato satā",
    "asallekhamasākhalye sīlādiguṇasobhinā ayaṃ samutinā sādhu yācitena kato satā",
    "rammasallekhasākhalya sīlādiguṇasobhinā ayaṃ sumatinā sādhu yācitena kato satā",
    "asallekhamasākhalye sīlādiguṇasobhinā ayaṃ sumatinā sādhu yācitena kato satā",
    "rammasallekhasākhalyā sīlādiguṇasobhitā ayaṃ sumatinā sādhu yācitena kato satā",
    "asallecamasākhalye sīlādiguṇasobhinā ayaṃ sumatinā sāra yācitena kato satā",
    "asallekhamasākhalye sīlādiguṇasobhinā ayaṃ sumatinā sādhu yācitena kato satā",
    "rammasallekhasākhalyā sīlādiguṇasobhinā ayaṃ sumatinā sādhu yācitena kato satā",
    "asallekhamasākhalye sīlādiguṇasobhinā ayaṃ sumatinā sādhu yācitena kato satā",
  ],
  [
    "devā kālena vassantu vassaṃ vassavalāhakā pālayantu mahīpālā dhammato sakalaṃ mahiṃ",
    "devā kālena vassantu vassaṃ vassavalāhakā pālayantu mahīpālā dhammato sakalaṃ mahiṃ",
    "devā kālena vassantu vassaṃ vassavalāhakā pāyalayantu mahīpālā dhammato sakalaṃ mahiṃ",
    "devā kālena vassantu vassaṃ vassavalāhakā pālayantu mahīpālā dhammato sakalaṃ mahiṃ",
    "devā kāle pavassantu vassaṃ vassavalāhakā pālayantu mahīpālā dhammato sakalam pati",
    "devā kālena vassantu vassaṃ vassavalāhakā pālantu mahīpālā dhammato sakalam pati",
    "devā kālena vassantu vassaṃ vassavalāhakā pālantu mahīpālā dhammato sakalam pati",
    "devā kālena vassantu vassaṃ vassavalāhakā pālayantu mahīpālā dhammato sakalaṃ mahiṃ",
    "devā kāle pavassantu vassaṃ vassaṃ vassavalāhakā pālayantu mahīpālā dhammato sakalam mahiṃ",
    "devā kālena vassantu vassaṃ vassavalāhakā pālayantu mahīpālā dhammato sakalaṃ mahiṃ",
    "devā kāle pavassantu vassaṃ vassavalāhakā pālayantu mahīpālā dhammato sakalaṃ mahiṃ",
    "devā kālena vasantu vassaṃ vassavalāhakā pālantu mahīpālā dhammato sakalaṃ mahi",
    "dovā kālena vassanta vassaṃ vassavalāhakā pālayantu mahīpālā dhammato sakalaṃ mahi",
    "devā kālena vassantu vassaṃ vassavalāhakā pālayantu mahīpālā dhammato sakalaṃ mahiṃ",
  ],
  [
    "yāva tiṭṭhati lokasmiṃ himavā pabbatuttamo tāva tiṭṭhatu saddhammo dhammarājassa satthuno ti",
    "yāva tiṭṭhati lokasmiṃ himavā pabbatuttamo tāva tiṭṭhatu saddhammo dhammarājassa satthuno ti",
    "yavādi tiṭṭhati lokasmiṃ himavā pabbatuttamo tāva tiṭṭhatu saddhammo dhammarājassa satthuno ti",
    "yāva tiṭṭhati lokasmiṃ himavā pabbatuttamo tāva tiṭṭhatu saddhammo dhammarājassa satthuno ti",
    "yāva tiṭṭhati lokasmiṃ himavā pabbatuttamo bhāva tiṭṭhatu saddhammo dhammarājassa satthuno ti",
    "yāva tiṭṭhati lokasmiṃ himavā pabbatuttamo tāva tiṭṭhatu saddhammo dhammarājassa satthuno ti",
    "yāva tiṭṭhati lokasmiṃ himavā pabbatuttamo tāva tiṭṭhatu saddhammo dhammarājassa satthuno ti",
    "yāva tiṭṭhati lokasmiṃ himavā pabbatuttamo tāva tiṭṭhakuttamo dhammarājassa satthuno ti",
    "yāva tiṭṭhati lokasmiṃ himavā pabbatuttamo tāva tiṭṭhatu saddhammo dhammarājassa satthuno ti",
    "yāva tiṭṭhati lokasmiṃ himavā pabbatuttamo tāva tiṭṭhatu saddhammo dhammarājassa satthuno ti",
    "yāva tiṭṭhati lokasmiṃ himavā pabbatukkamo tāva tiṭṭhatu saddhammo dhammarājassa satthuno ti",
    "yāva tiṭṭhati lokasmiṃ himavā pabbatuttamo tāva tiṭṭhatu saddhammo dhammarājassa satthuno ti",
    "yāva tiṭṭhati lokasmiṃ himavā pabbatutthamo hāva tiṭṭhatu saddhammo dhammarājassa sattuno ti",
    "yāva tiṭṭhati lokasmiṃ himavā pabbatuttamo tāva tiṭṭhatu saddhammo dhammarājassa satthuno ti",
  ],
  ["", "", "", "", "", "", "", "", "", "", "", "", "", ""],
];
