var editionIds = [
  "CS",
  "PTS",
  "G",
  "A",
  "B",
  "I",
  "C",
  "D",
  "E",
  "F",
  "H",
  "K",
];

var bibleEditions = [
  "CS",
  "PTS",
  "G",
  "A",
  "B",
  "I",
  "C",
  "D",
  "E",
  "F",
  "H",
  "K",
];

var verses = "11 - 20";

var bibleVerses = [
  [
    "<11> cheke kusalasaddoyaṃ ārogye anavajjake diṭṭho iṭṭhavipāke pi anavajjādike idha tasmā anavajjaiṭṭhavipākalakkhaṇaṃ kusalaṃ akusalaviddhaṃsanarasaṃ vodānapaccupaṭṭhānaṃ vajjapaṭipakkhattā anavajja lakkhaṇaṃ vā kusalaṃ vodānabhāvarasaṃ iṭṭhavipākapaccupaṭṭhānaṃ yonisomanasikārapadaṭṭhānaṃ sāvajjāniṭṭhavipākalakkhaṇam akusalaṃ tadubhayaviparītalakkhaṇam abyākataṃ avipākārahaṃ vā tattha kusalacittaṃ ekavīsatividhaṃ hoti tadidaṃ bhūmito catubbidhaṃ hoti kāmāvacaraṃ rūpāvacaraṃ arūpāvacaraṃ lokuttarañ ceti tattha kāmāvacara kusala cittaṃ bhūmito ekavidhaṃ savatthukāvatthukabhedato duvidhaṃ hīnamajjhimapaṇītabhedato tividhaṃ somanassupekkhāñāṇappayogabhedato aṭṭhavidhaṃ hoti seyyathidaṃ somanassasahagataṃ ñāṇasampayuttaṃ asaṅkhārikam ekaṃ sasaṅkhārikam ekaṃ somanassasahagataṃ ñāṇavippayuttaṃ asaṅkhārikamekaṃ sasaṅkhārikamekaṃ upekkhāsahagataṃ ñāṇasampayuttaṃ asaṅkhārikam ekaṃ sasaṅkhārikam ekaṃ upekkhāsahagataṃ ñāṇavippayuttaṃ asaṅkhārikam ekaṃ sasaṅkhārikam ekan ti idaṃ aṭṭhavidham pi kāmāvacarakusalacittaṃ nāma ",
    "<11> cheke kusalasaddoyaṃ ārogye anavajjake diṭṭho iṭṭhavipāke ca; anavajjādike idha tasmā anavajjaiṭṭhavipākalakkhaṇaṃ kusalaṃ akusalaviddhaṃsanarasaṃ vodānapaccupaṭṭhānaṃ; sāvajjapaṭipakkhattā anavajjam eva lakkhaṇaṃ vā kusalaṃ vodānabhāvarasaṃ iṭṭhavipākapaccupaṭṭhānaṃ yonisomanasikārapadaṭṭhānaṃ sāvajjāniṭṭhavipākalakkhaṇaṃ akusalaṃ tadubhayaviparitalakkhaṇam abyākataṃ avipākārahaṃ vā tattha kusalacittaṃ ekavīsatividhaṃ hoti tadidaṃ bhūmito catubbidhaṃ hoti kāmāvacaraṃ rūpāvacaraṃ arūpāvacaraṃ lokuttarañ ceti tattha kāmāvacaraṃ kusalaṃ cittaṃ bhūmito ekavidhaṃ; savatthukāvatthukabhedato duvidhaṃ; hīnamajjhimapaṇītabhedato tividhaṃ; somanassupekkhāñāṇasaṅkhārasampayogavippayogabhedato aṭṭhavidhaṃ hoti; seyyathidaṃ somanassasahagataṃ ñāṇasampayuttaṃ asaṅkhārikam ekaṃ sasaṅkhārikam ekaṃ somanassasahagataṃ ñāṇavippayuttaṃ asaṅkhārikamekaṃ sasaṅkhārikamekaṃ upekkhāsahagataṃ ñāṇasampayuttaṃ asaṅkhārikam ekaṃ sasaṅkhārikam ekaṃ upekkhāsahagataṃ ñāṇavippayuttaṃ asaṅkhārikam ekaṃ sasaṅkhārikam ekan ti idaṃ aṭṭhavidham pi kāmāvacarakusalacittaṃ nāma ",
    "<11> cheke kusalasaddoyaṃ ārogye anavajjake diṭṭho iṭṭhavipāke ca; anavajjādike idha tasmā anavajjaiṭṭhavipākalakkhaṇaṃ kusalaṃ akusalaviddhaṃsanarasaṃ vodānapaccupaṭṭhānaṃ; sāvajjapaṭipakkhattā anavajja lakkhaṇam eva vā kusalaṃ vodānabhāvarasaṃ iṭṭhavipākapaccupaṭṭhānaṃ yonisomanasikārapadaṭṭhānaṃ sāvajjāniṭṭhavipākalakkhaṇaṃ akusalaṃ tadubhayaviparitalakkhaṇam abyākataṃ avipākārahaṃ vā tattha kusalacittaṃ ekavīsatividhaṃ hoti tayidaṃ bhūmito catubbidhaṃ hoti kāmāvacaraṃ rūpāvacaraṃ arūpāvacaraṃ lokuttarañ ceti tattha kāmāvacara kusala cittaṃ bhūmito ekavidhaṃ; savatthukāvatthukabhedato duvidhaṃ; hīnamajjhimapaṇītabhedato tividhaṃ; somanassupekkhāñāṇasampayogavippayogādibhedato aṭṭhavidhaṃ hoti; seyyathīdaṃ somanassasahagataṃ ñāṇasampayuttaṃ asaṃkhārikam ekaṃ sasaṃkhārikam ekaṃ somanassasahagataṃ ñāṇavippayuttaṃ asaṃkhārikamekaṃ sasaṃkhārikamekaṃ upekkhāsahagataṃ ñāṇasampayuttaṃ asaṃkhārikam ekaṃ sasaṃkhārikam ekaṃ upekkhāsahagataṃ ñāṇavippayuttaṃ asaṃkhārikam ekaṃ sasaṃkhārikam ekan ti idaṃ aṭṭhavidham kāmāvacarakusalacittaṃ nāma ",
    "<11> cheke kusalasaddoyaṃ ārogye anavajjake diṭṭho iṭṭhavipāke pi anavajjādike idha tasmā anavajjaiṭṭhavipākalakkhaṇaṃ kusalaṃ akusalaviddhaṃsanarasaṃ vodānapaccupaṭṭhānaṃ; vajjapaṭipakkhattā anavajja lakkhaṇaṃ vā kusalaṃ vodānabhāvarasaṃ iṭṭhavipākapaccupaṭṭhānaṃ yonisomanasikārapadaṭṭhānaṃ sāvajjāniṭṭhavipākalakkhaṇam akusalaṃ tadubhayaviparitalakkhaṇam abyākataṃ avikārahaṃ vā tattha kusalacittaṃ ekavīsatividhaṃ hoti tadidaṃ bhūmito catubbidhaṃ hoti kāmāvacaraṃ rūpāvacaraṃ arūpāvacaraṃ lokuttarañ ceti tattha kāmāvacara kusala cittaṃ bhūmito ekavidhaṃ; savatthukāvatthukabhedato duvidhaṃ; hīnamajjhimapaṇītabhedato tividhaṃ; somanassupekkhāñāṇappayogabhedato aṭṭhavidhaṃ hoti; seyyathidaṃ somanassasahagataṃ ñāṇasampayuttaṃ asaṅkhārikam ekaṃ sasaṅkhārikam ekaṃ somanassasahagataṃ ñāṇavippayuttaṃ asaṅkhārikamekaṃ sasaṅkhārikamekaṃ upekkhāsahagataṃ ñāṇasampayuttaṃ asaṅkhārikam ekaṃ sasaṅkhārikam ekaṃ upekkhāsahagataṃ ñāṇavippayuttaṃ asaṅkhārikam ekaṃ sasaṅkhārikam ekan ti idaṃ aṭṭhavidham pi kāmāvacarakusalacittaṃ nāma ",
    "<11> cheke kusalasaddoyaṃ ārogye avanajjake diṭṭho idha vipāke pi anavajjādike idha tasmā anavajjādike iṭṭhavipākalakkhaṇaṃ kusalaṃ kusalaṃ viddhaṃsanarasaṃ vodānapaccupaṭṭhānaṃ; vajjapaṭipakkhattā anavajjam eva lakkhaṇaṃ vā kusalaṃ vodānabhāvarasaṃ iṭṭhavipākapaccupaṭṭhānaṃ yonisomanasikārapadaṭṭhānaṃ sāvajjāniṭṭhavipākalakkhaṇam akusalaṃ tadubhayaviparitalakkhaṇam abyākataṃ avipākārasaṃ vā tattha kusalacittaṃ ekaṃ vīsatividhaṃ hoti taṃ didaṃ bhumito catubbidhaṃ hoti kāmāvacaraṃ rūpāvacaraṃ arūpāvacaraṃ lokuttarañ ceti tattha kāmāvacaraṃ kusalaṃ cittaṃ bhūmito ekavidhaṃ hoti savatthukāvatthukabhedato duvidhaṃ; hīnamajjimaṇītabhedato tividaṃ; somanussupekkhāññāṇasaṅkhārasampayogavippayogabhedato aṭṭhavidhaṃ hoti; seyyathidaṃ somanassasahagataṃ ññāṇasampayuttaṃ asaṅkhārikam ekaṃ sasaṅkhārikam ekaṃ somanassasahagataṃ ññāṇavippayuttaṃ asaṅkhārikamekaṃ sasaṅkhārikamekaṃ upekkhāsahagataṃ ññāṇasampayuttaṃ asaṅkhārikam ekaṃ sasaṅkhārikam ekaṃ upekkhāsahagataṃ ññāṇavippayuttaṃ asaṅkhārikam ekaṃ sasaṅkhārikam ekan ti idhaṃ aṭṭhavidham pi kāmāvacarakusalacittaṃ nāma ",
    "<11> cheke kusalasaddoyaṃ ārogye anavajjake diṭṭho iṭṭhavipāka pi anavajjādike idha tasmā anavajjādikaṃ iṭṭhavipākalakkhaṇaṃ kusalaṃ akusalaviddhaṃsanarasaṃ vodānapaccupaṭṭhānaṃ; vajjapaṭipakkhattā anavajja lakkhaṇaṃ vā kusalaṃ vodānabhāvarasaṃ iṭṭhavipākapaccupaṭṭhānaṃ yonisomanasikārapadaṭṭhānaṃ sāvajjāniṭṭhavipākalakkhaṇam akusalaṃ tadubhayaviparitalakkhaṇam abyākataṃ avipākārahaṃ vā tattha kusalacittaṃ ekavīsatividhaṃ hoti tadidaṃ bhūmito catubbidhaṃ hoti kāmāvacaraṃ rūpāvacaraṃ arūpāvacaraṃ lokuttarañ ceti tattha kāmāvacaraṃ kusala cittaṃ bhūmito ekavidhaṃ; savatthukāvatthukabhedato duvidhaṃ; hīnamajjhimapaṇītabhedato tividhaṃ; somanassupekkhāñāṇasaṅkhārasampayogavippayogabhedato aṭṭhavidhaṃ hoti; seyyathidaṃ somanassasahagataṃ ñāṇasampayuttaṃ asaṅkhārikam ekaṃ sasaṅkhārikam ekaṃ somanassasahagataṃ ñāṇavippayuttaṃ asaṅkhārikamekaṃ sasaṅkhārikamekaṃ upekkhāsahagataṃ ñāṇasampayuttaṃ asaṅkhārikam ekaṃ sasaṅkhārikam ekaṃ upekkhāsahagataṃ ñāṇavippayuttaṃ asaṅkhārikam ekaṃ sasaṅkhārikam ekan ti idaṃ aṭṭhavidham pi kāmāvacarakusalacittaṃ nāma ",
    "<11> cheke kusalasaddoyaṃ ārogye anavajjake diṭṭho iṭṭhavivipāke pi anavajjādike idha tasmā anavajjādikaṃ iṭṭhavipākalakkhaṇaṃ kusalaṃ akusalaviddhaṃsanarasaṃ vodānapaccupaṭṭhānaṃ; vajjapaṭipakkhattā anavajja lakkhaṇaṃ vā kusalaṃ vodānabhāvarasaṃ iṭṭhavipākapaccupaṭṭhānaṃ yonisomanasikāravadaṭṭhānaṃ sāvijjāniṭṭhavipākalakkhaṇam akusalaṃ tadubhayaviparitalakkhaṇam abyākataṃ avipākarahaṃ vā tattha kusalacittaṃ ekavīsatividhaṃ hoti tadidaṃ bhūmito catubbidhaṃ hoti kāmāvacaraṃ rūpāvacaraṃ arūpāvacaraṃ sokuttarañ ceti tattha kāmāvacara kusala cittaṃ bhūmito ekavidhaṃ; savatthukāvatthukabhedato duvidhaṃ; hīnamajjhimapaṇīdhatedato tividhaṃ; somanassupekkhāñāṇasaṅkhārasampayogavippayogabhedato aṭṭhavidhaṃ hoti; seyyatidaṃ somanassasahagataṃ ñāṇasampayuttaṃ asaṅkhārikam ekaṃ sasaṅkhārikam ekaṃ somanassasahagakaṃ ñāṇavippayuttaṃ asaṅkhārikamekaṃ sasaṅkhārikamekaṃ upekkhāsahagataṃ ñāṇasampayuttaṃ asaṅkhārikam ekaṃ sasaṅkhārikam ekaṃ upekkhāsahagataṃ ñāṇavippayuttaṃ asaṅkhārikam ekaṃ sasaṅkhārikam ekan ti idaṃ aṭṭhavidham mi kāmāvacarakusalacittaṃ nāma ",
    "<11> cheke kusalasaddoyaṃ ārogye anavajjake diṭṭho iṭṭhavipāke ca; anavajjādike idha tasmā anavajjaiṭṭhavipākalakkhaṇaṃ kusalaṃ akusalaviddhaṃsanarasaṃ vodānapaccupaṭṭhānaṃ; vajjapaṭipakkhattā anavajja lakkhaṇam eva vā kusalaṃ vodānabhāvarasaṃ iduṭṭhavipākapaccupaṭṭhānaṃ yonisomanasikārapadaṭṭhānaṃ sāvajjāniṭṭhavipākalakkhaṇam akusalaṃ tadubhayaviparitalakkhaṇam abyākataṃ avipākārahaṃ vā tattha kusalacittaṃ ekavīsatividhaṃ hoti tadidaṃ bhūmito catubbidhaṃ hoti kāmāvacaraṃ rūpāvacaraṃ arūpāvacaraṃ lokuttarañ ceti tattha kāmāvacaraṃ kusala cittaṃ bhūmito ekavidhaṃ; savatthukāvatthukabhedato duvidhaṃ; hīnamajjhimapaṇītabhedato tividhaṃ; somanassuñāṇappayogabhedato aṭṭhavidhaṃ hoti; seyyathidaṃ somanassasahagataṃ ñāṇasampayuttaṃ asaṃkhārikam ekaṃ sasaṃkhārikam ekaṃ somanassasahagataṃ ñāṇavippayuttaṃ asaṃkhārikamekaṃ sasaṃkhārikamekaṃ upekkhāsahagataṃ ñāṇasampayuttaṃ asaṃkhārikam ekaṃ sasaṃkhārikam ekaṃ upekkhāsahagataṃ ñāṇavippayuttaṃ asaṃkhārikam ekaṃ sasaṃkhārikam ekaṃ ti idaṃ aṭṭhavidham pi kāmāvacarakusalacittaṃ nāma ",
    "<11> cheke kusalasaddoyaṃ ārogye avanajjale diṭṭho iṭṭhavipāke pi anavajjādike idha tasmā anavajjaiṭṭhavipākalakkhaṇaṃ kusalaṃ akusalaviddhaṃsanarasaṃ vodānapaccupaṭṭhānaṃ; vajjapaṭipakkhattā anavajjam eva lakkhaṇaṃ vā kusalaṃ vodānabhāvarasaṃ iṭṭhavipākapaccupaṭṭhānaṃ yonisomanasikārapadaṭṭhānaṃ sāvajjāniṭṭhavipākalakkhaṇam akusalaṃ tadubhayaviparitalakkhaṇam abyākataṃ avipākarahaṃ vā tattha kusalacittaṃ ekavīsatividhaṃ hoti tadidaṃ bhummito catubbidhaṃ hoti kāmāvacaraṃ rūpāvacaraṃ arūpāvacaraṃ lokuttarañ ceti tattha kāmāvacaraṃ kusalaṃ cittaṃ bhūmito ekavidhaṃ hoti savatthukāvatthukabhedato duvidhaṃ; hīnamajjhimapaṇītabhedato tividhaṃ; somanassupekkhāñāṇappayogabhedato aṭṭhavidhaṃ hoti; seyyathidaṃ somanassasahagataṃ ñāṇasampayuttaṃ asaṅkhārikam ekaṃ sasaṅkhārikam ekaṃ somanassasahagataṃ ñāṇavippayuttaṃ asaṅkhārikamekaṃ sasaṅkhārikamekaṃ upekkhāsahagataṃ ñāṇasampayuttaṃ asaṅkhārikam ekaṃ sasaṅkhārikam ekaṃ upekkhāsahagataṃ ñāṇavippayuttaṃ asaṅkhārikam ekaṃ sasaṅkhārikam ekan ti idaṃ aṭṭhavidham pi kāmāvacarakusalacittaṃ nāma ",
    "<11> cheke kusalasaddoyaṃ ārogye anavajjake diṭṭho iṭṭhavipāke ca; anavajjādike idha tasmā anavajjaiṭṭhavipākalakkhaṇaṃ kusalaṃ akusalaviddhaṃsanarasaṃ vodānapaccupaṭṭhānaṃ; sāvajjapaṭipakkhattā anavajjam eva lakkhaṇaṃ vā kusalaṃ vodānabhāvarasaṃ iṭṭhavipākapaccupaṭṭhānaṃ yonisomanasikārapadaṭṭhānaṃ sāvajjāniṭṭhavipākalakkhaṇam akusalaṃ tadubhayaviparitalakkhaṇam abyākataṃ avipākārahaṃ vā tattha kusalacittaṃ ekavīsatividhaṃ hoti tadidaṃ bhūmito catubbidhaṃ hoti kāmāvacaraṃ rūpāvacaraṃ arūpāvacaraṃ lokuttarañ ceti tattha kāmāvacara kusalaṃ cittaṃ bhūmito ekavidhaṃ hoti savatthukāvatthukabhedato duvidhaṃ; hīnamajjhimapaṇitabhedato tividhaṃ; somanassapekkhāñāṇasaṃkhārapayogavippayogabhedato aṭṭhavidhaṃ hoti; seyyathidaṃ somanassasahagataṃ ñāṇasampayuttaṃ asaṅkhārikam ekaṃ sasaṅkhārikam ekaṃ somanassasahagataṃ ñāṇavippayuttaṃ asaṅkhārikamekaṃ sasaṅkhārikamekaṃ upekkhāsahagataṃ ñāṇasampayuttaṃ asaṅkhārikam ekaṃ sasaṅkhārikam ekaṃ upekkhāsahagataṃ ñāṇavippayuttaṃ asaṅkhārikam ekaṃ sasaṅkhārikam ekan ti idaṃ aṭṭhavidham pi kāmāvacarakusalacittaṃ nāma ",
    "<11> cheke kusalasaddoyaṃ ārogye anavajjake diṭṭho iṭṭhavipāke pi anavajjādike idha tasmā anavajjaiṭṭhavipākalakkhaṇaṃ kusalaṃ akusalaviddhaṃsanarasaṃ vodānapaccupaṭṭhānaṃ; vajjapaṭipakkhattā anavajja lakkhaṇam eva vā kusalaṃ vodānabhāvarasaṃ iṭṭhavipākapaccupaṭṭhānaṃ yonisomanasikārapadaṭṭhānaṃ sāvajjāniṭṭhavipākalakkhaṇam akusalaṃ tadubhayaviparitalakkhaṇam abyākataṃ avipākārahaṃ vā tattha kusalacittaṃ etavīsatividhaṃ hoti tadidaṃ bhūmito catubbidhaṃ hoti kāmāvacaraṃ rūpāvacaraṃ arūpāvacaraṃ lotuttarañ ceti tattha kāmāvacaraṃ kusala cittaṃ bhūmito ekavidhaṃ; savatthukāvatthukabhedato duvidhaṃ; hīnamajjhimapaṇītabhedato tividhaṃ; somanassupekkhāñāṇappayogabhedato aṭṭhavidhaṃ hoti; seyyathidaṃ somanassasahagataṃ ñāṇasampayuttaṃ asaṅkhārikam ekaṃ sasaṅkhārikam ekaṃ somanassasahagataṃ ñāṇavippayuttaṃ asaṅkhārikamekaṃ sasaṅkhārikamekaṃ upekkhāsahagataṃ ñāṇasampayuttaṃ asaṅkhārikam ekaṃ sasaṅkhārikam ekaṃ upekkhāsahagataṃ ñāṇavippayuttaṃ asaṅkhārikam ekaṃ sasaṅkhārikam ekan ti idaṃ aṭṭhavidham pi kāmāvacarakusalacittaṃ nāma ",
    "<11> cheke kusalasaddoyaṃ ārogye anavajjake niṭṭhe iṭṭhavipāke ca; anavajjādike idha tasmā anavajjaiṭṭhavipākalakkhaṇaṃ kusalaṃ akusalaviddhaṃsanarasaṃ vodānapaccupaṭṭhānaṃ; sāvajjapaṭipakkhattā anavajjam eva lakkhaṇaṃ vā kusalaṃ vodānabhāvarasaṃ iṭṭhavipākapaccupaṭṭhānaṃ yonisomanasikāyapadaṭṭhānaṃ sāvajjāniṭṭhaṃ vipākalakkhaṇaṃ akusalaṃ tadubhayaviparitalakkhaṇam abyākataṃ avipākārahaṃ vā tattha kusalaṃ cittaṃ ekavīsatividhaṃ hoti taditaṃ bhūmito catubbidhaṃ hoti kāmāvacaraṃ rūpāvacaraṃ arūpāvacaraṃ lokuttarañ ceti tattha kāmāvacaraṃ kusalaṃ cittaṃ bhūmito ekavidhaṃ; savatthukāvatthukabhedato duvidhaṃ; hīnamajjhimapaṇītabhedato tividhaṃ; somanassupekkhāñāṇapayogabhedato aṭṭhavidhaṃ hoti; seyyathidaṃ somanassasahagataṃ ñāṇasampayuttaṃ asaṃkhārikam ekaṃ sasaṃkhārikam ekaṃ somanassasahagataṃ ñāṇavippayuttaṃ asaṅkhārikamekaṃ sasaṅkhārikamekaṃ upekkhāsahagataṃ ñāṇasampayuttaṃ asaṅkhārikam ekaṃ sasaṅkhārikam ekaṃ upekkhāsahagataṃ ñāṇavippayuttaṃ asaṅkhārikam ekaṃ sasaṅkhārikam ekan ti idaṃ aṭṭhavidham pi kāmāvacarakusalacittaṃ nāma ",
  ],
  [
    "<12> uddānato duve kāmā klesavatthuvasā pana kileso chandarāgo va vatthu tebhūmavaṭṭakaṃ",
    "<12> uddānato duve kāmā klesavatthuvasā pana kileso chandarāgo va vatthu tebhūmavaṭṭakaṃ",
    "<12> udānato dave kāmā klesavatthuvasā pana kileso chandarāto va vatthu tebhūmivaṭṭakaṃ",
    "<12> uddānato duve kāmā klesavatthuvasā pana kileso chandarāgo va vatthu tebhūmavaṭṭakaṃ",
    "<12> uddānato duve kāmā kilesavatthuvasā pana kileso chandarāgo ca vatthu tebhūmavaṭṭakaṃ",
    "<12> udānato duve kāmā kilesavatthuvasā pana kileso chandarāgo va vatthu tebhūmavaṭṭakaṃ",
    "<12> udānato duve kāmā kilesavatthuvasā pana kileso chandarāgo va vatthu tebhūmavaṭṭakaṃ",
    "<12> uddānato duve kāmā klesavatthuvasā pana kileso chandarāgo va vatthu tebhūmavaṭṭakaṃ",
    "<12> uddānato duve kāmā kilesavatthuvasā pana kileso chandarāgo ca vatthu tebhūmmavaṭṭakaṃ",
    "<12> udānato duve kāmā klesavatthuvasā pana kileso chandarāgo ca vatthu tebhūmakavaṭṭaṃ",
    "<12> udānato duve kāmā lesavatthuvasā pana kileso chandarāgo va vatthu tebhūmavaṭṭakaṃ",
    "<12> udānato duve kāmā kilesavatthuvasā pana kileso chandarāgo va vatthu tebhūmavaṭṭakaṃ",
  ],
  [
    "<13> kilesakāmo kāmeti vatthu kāmīyatī ti ca sijjhati duvidho pesa kāmo vo kārakadvaye",
    "<13> kilesakāmo kāmeti vatthu kāmīyatī ti ca sijjhati duvidho pesa kāmo vo kārakadvaye",
    "<13> kilesakāmo kāmeti vatthu kāmīyatī ti ca sijjhati duvidho pesa kāmo vo kārakadvaye",
    "<13> kilesakāmo kāmeti vatthu kāmīyatī ti ca sijjhati duvidho pesa kāmo vo kārakadvaye",
    "<13> kilesakāmo kāmeti vatthu kāmīyatī ti ca sijjhati duvidho pesa kāmo vo kārakadvaye",
    "<13> kilesakāmo kāmeti vatthu kāmiyatī ti ca sijjhati duvidho pesa kāmo vo kārakadvaye",
    "<13> kilesākāmo kāmeti vatthu kāmīyatī ti ca sijjhati duvidho pesa kāmo vo kārakadvaye",
    "<13> kilesakāmo kāmeti vatthu kāmīyatī ti ca sijjhati duvidho pesa kāmo vo kārakadvaye",
    "<13> kilesakāmo kāmeti vatthu kāmīyatī ti ca sijjhati duvidho pesa kāmo vo kārakadvaye",
    "<13> kilesakāmo kāmeti vatthu kāmīyatī ti ca sijjhati duvidho pesa kāmo vo kārakadvaye",
    "<13> kilesakāmo kāmeti vatthu kāmīyatī ti ca sijjhate duvidho pesa kāmo vo kārakadvaye",
    "<13> kilesa kāmeti vatthu kāmiyatī ti ca sijjhati dūvito pesa kāmā vo kārakadvaye",
  ],
  [
    "<14> yasmiṃ pana padese so kāmo yaṃ duvidho pi ca sampattīnaṃ vasenāvacaratī ti ca so pana ",
    "<14> yasmiṃ pana padese so kāmo yaṃ duvidho pi ca sampattīnaṃ vasenāvacaratī/vasen eva carati ti ca so pana",
    "<14> yasmiṃ pana padese so kāmo yaṃ dubbidho pi ca sampattīnaṃ vasenāvacaratī ti ca so pana ",
    "<14> yasmiṃ pana padese so kāmo yaṃ duvidho pi ca sampattīnavasenāvacaratī ti ca so pana",
    "<14> yasmiṃ pana padese so kāmo yaṃ duvidho pi ca sampattīnaṃ vasenāvacaratī ti ca so pana ",
    "<14> yasmiṃ pana padese so kāmo yaṃ duvidho pi ca sampattīnaṃ vasenāvacaratī ti ca so pana ",
    "<14> yasmiṃ pana padese so kāmo yaṃ duvidho pi ca sampattīnaṃ vasenāvacaratī ti ca so pana ",
    "<14> yasmiṃ pana padese so kāmo yaṃ duvidho pi ca sampattīnaṃ vasenāvacaratī ti ca so pana ",
    "<14> yasmiṃ pana padese so kāmo yaṃ duvidho pi ca sampattīnaṃ vasenāvacaratī ti ca so pana ",
    "<14> yasmiṃ pana dese so kāmo yaṃ duvidho pi ca sampattīnaṃ vaseneva caratī ti ca so pana ",
    "<14> yasmiṃ pana padese so kāmo yaṃ duvidho pi ca sampattīnaṃ vasenāvacaratī ti ca so pana ",
    "<14> yasmiṃ pana desese so kāmo yaṃ duvidho pi ca sampattinaṃ vasenevacaratī ti ca so pana ",
  ],
  [
    "<15> padeso catupāyānaṃ channaṃ devānam eva ca manussānaṃ vasen eva ekādasavidho pana",
    "<15> padeso catupāyānaṃ/caturapāyānaṃ channaṃ devānam eva ca manussānaṃ vasen eva ekādasavidho pana",
    "<15> padeso catupāyānaṃ channaṃ devānam eva ca manussānaṃ vasechāpi ekādasavidho pana ",
    "<15> padeso catupāyānaṃ channaṃ dvevānam eva ca manussānaṃ vasen eva ekādasavidho pana",
    "<15> padeso catupāyānaṃ channaṃ devānam eva ca manussānaṃ vasen eva ekādasavidho pana",
    "<15> padeso catupāyānaṃ channaṃ devānam eva ca manussānaṃ vasen eva ekādasavidho pana",
    "<15> padeso catupāyānaṃ channaṃ devānam eva ca manussānaṃ vasen eva ekādasavidho pana",
    "<15> padeso catupāyānaṃ channaṃ devānam eva ca manussānaṃ vasen eva ekādasavidho pana",
    "<15> padeso catupāyānaṃ channaṃ devānam eva ca manussānaṃ vasen eva ekādasavidho pana",
    "<15> padeso catupāyānaṃ channaṃ devānam eva ca manussānaṃ vasen eva ekādasavidho pana",
    "<15> padeso catupāyānaṃ channaṃ devānam eva ca manussānaṃ vasen eva ekādasavidho pana",
    "<15> padeso catupāyānaṃ channaṃ devānam eva ca manussānaṃ vasen eva ekādasavidho pana",
  ],
  [
    "<16> kāmo vacaratī t ettha kāmāvacarasaññito assābhilakkhitattā hi sasatthāvacaro viya ",
    "<16> kāmo vacaratī t ettha kāmāvacarasaññito assābhilakkhitattā hi sasatthāvacaro viya",
    "<16> kāmo vacaratī t ettha kāmāvacarasaññito assābhilakkhitattā hi sasatthāvacaro viya ",
    "<16> kāmo vacaratī t ettha kāmāvacarasaññito assābhilakkhitattā hi sasatthāvacaro viya ",
    "<16> kāmo vacaratī t ettha kāmāvacarasaññito assābhilakkhitattā hi sasatthāvacaro viya ",
    "<16> kāmo vacaratī t ettha kāmāvacarasaññito assābhilakkhitattā hi saṃsattāvacaro viya ",
    "<16> kāmo vacaratī t ettha kāmāvacarasaññito assātilakkhitattā hi sabhatthāvacaro viya ",
    "<16> kāmo vacaratī t etta kāmāvacarasaññito assābhilakkhitattā hi sasatthāvacaro viya ",
    "<16> kāmo vacaratī t ettha kāmāvacarasaññito assātilakkhitattā hi sasatthāvacaro viya ",
    "<16> kāmo vacaratī t ettha kāmāvacarasaññito assābhilakkhitattā hi satthāvacaro viya ",
    "<16> kāmo vacaratī t ettha kāmāvacarasaññito assābhilakkhitattā hi sasatthāvacaro viya ",
    "<16> kāmo carati t ettha kāmāvacarasaññito assabhilakkhitattā ti sasatthāvacaro viya ",
  ],
  [
    "<17> svāyaṃ rūpabhavo rūpaṃ evaṃ kāmo ti saññito uttarassa padass eva lopaṃ katvā udīrito",
    "<17> svāyaṃ rūpabhavo rūpaṃ evaṃ kāmo ti saññito uttarassa padass eva lopaṃ katvā udīrito",
    "<17> svāyaṃ rūpabhavo rūpaṃ evaṃ kāmo ti saññito uttarassa padassa sa lopaṃ katvā udīrito",
    "<17> svāyaṃ rūpabhavo rūpaṃ evaṃ kāmo ti saññito uttarassa padass eva lopaṃ katvā udīrito",
    "<17> svāyaṃ rūpabhavo rūpaṃ evaṃ kāmo ti saññito uttarassa padass eva lopaṃ katvā udīrito",
    "<17> svāyaṃ rūpabhavo rūpaṃ evaṃ kāmo ti saññito uttarassa padass eva lopaṃ katvā udīrito",
    "<17> svāyaṃ rūpabhavo rūpaṃ evaṃ kāmo ti saññito uttarassa padass eva lopaṃ katvā udīrito",
    "<17> svāyaṃ rūpabhavo rūpaṃ evaṃ kāmo ti saññito uttarassa padass eva lopaṃ katvā udīrito",
    "<17> svāyaṃ rūpabhavo rūpaṃ evaṃ kāmo ti saññito uttarassa padass eva lopaṃ katvā udīrito",
    "<17> svāyaṃ rūpabhavo rūpaṃ evaṃ kāmo ti saññito uttarassa padass eva lopaṃ katvā udīrito",
    "<17> svāyaṃ rūpabhavo rūpaṃ evaṃ kāmo ti saññito uttarassa padass eva lopaṃ katvā udīrito",
    "<17> svāyaṃ rūpabhavo rūpaṃ evaṃ kāmo ti saññito uttarassa padess eva lopaṃ katvā udirito",
  ],
  [
    "<18> tasmiṃ kāme idaṃ cittaṃ sadā vacaratī ti ca kāmāvacaram icc evaṃ kathitaṃ kāmaghātinā ",
    "<18> tasmiṃ kāme idaṃ cittaṃ sadā vacaratī ti ca kāmāvacaram icc evaṃ kathitaṃ kāmaghātinā ",
    "<18> tasmiṃ kāme c idaṃ cittaṃ sadā vacaratī ti ca kāmāvacaram icc evaṃ kathitaṃ kāmaghātinā",
    "<18> tasmiṃ kāme idaṃ cittaṃ sadā vacaratī ti ca kāmāvacaram icc evaṃ kathitaṃ kāmaghātinā ",
    "<18> tasmiṃ kāme idaṃ mahācittaṃ sadā vacaratī ti ca kāmāvacaram icc evaṃ kathitaṃ kāmaghātinā ",
    "<18> tasmiṃ kāme idaṃ cittaṃ sadā vacaratī ti ca kāmāvacaram icc evaṃ kathitaṃ kāmaghātinā ",
    "<18> tasmiṃ kāme idaṃ cittaṃ sadā vacaratī ti ca kāmāvacaram icc evaṃ kathitaṃ kāmaghātinā ",
    "<18> tasmiṃ kāme idaṃ cittaṃ sadā vacaratī ti ca kāmāvacaram icc evaṃ kathitaṃ kāmaghātinā ",
    "<18> tasmiṃ kāme idaṃ cittaṃ sadā vacaratī ti ca kāmāvacaram icc evaṃ kathitaṃ kāmaghātinā ",
    "<18> tasmiṃ kāme idaṃ cittaṃ sadā vacaratī ti ca kāmāvacaram icc evaṃ kathitaṃ kāmaghātinā ",
    "<18> tasmiṃ kāme idaṃ cittaṃ sadā vacaratī ti ca kāmāvacaram icc evaṃ kathitaṃ kāmaghātinā ",
    "<18> tasmiṃ kāme idaṃ cittaṃ sadā vacaratī ti ca kāmāvacaram icc evaṃ kathitaṃ kāmaghātinā ",
  ],
  [
    "<19> paṭisandhiṃ bhave kāme avacārayatī ti vā kāmāvacaram icc evaṃ pariyāpannan ti tatra vā",
    "<19> paṭisandhiṃ bhave kāme avacārayatī ti vā kāmāvacaram icc evaṃ pariyāpannan ti tatra vā",
    "<19> paṭisandhiṃ bhave kāme avacāriyatī ti vā kāmāvacaram icc evaṃ pariyāpannan ti tatha vā",
    "<19> paṭisandhiṃ bhave kāme avacārayatī ti vā kāmāvacaram icc evaṃ pariyāpannan ti tatra vā",
    "<19> paṭisandhiṃ bhave kāme avacārayatī vā kāmāvacaram icc evaṃ pariyāpannan ti tra vā ",
    "<19> paṭisandhiṃ bhave kāme avacārayatī ti vā kāmāvacaram icc evaṃ pariyāpannan ti tatra vā",
    "<19> paṭisandhiṃ bhave kāme avacārayatī ti vā kāmāvacaram icc evaṃ pariyāpannan ti tatra vā",
    "<19> paṭisandhibhave kāme avacārayatī ti vā kāmāvacaram icc eva pariyāpannan ti tatra vā ",
    "<19> paṭisandhiṃ bhave kāme avacārayatī ti vā kāmāvacaram icc evaṃ pariyāpannan ti tatra vā",
    "<19> paṭisandhiṃ bhave kāme avacārayatī ti vā kāmāvacaram icc evaṃ pariyāpannan ti tatra vā",
    "<19> paṭisandhiṃ bhave kāme avacārayatī ti vā kāmāvacaram icc evaṃ pariyāpannan ti tatra vā",
    "<19> paṭisandhiṃ bhave kāme avacārayatī ti vā kāmāvacaram icc evaṃ pariyāpannan ti tatra vā",
  ],
  [
    "<20 idaṃ aṭṭhavidhaṃ cittaṃ kāmāvacarasaññitaṃ dasapuññakriyavatthuvasen eva pavattati",
    "<20 idaṃ aṭṭhavidhaṃ cittaṃ kāmāvacarasaññitaṃ dasapuññakriyāvatthuvasen eva pavattati",
    "<20 idaṃ aṭṭhavidhaṃ cittaṃ kāmāvacarasaññitaṃ dasapuññakriyāvatthuvasen eva pavattati",
    "<20 idaṃ aṭṭhavidhaṃ cittaṃ kāmāvacarasaññitaṃ dasapuññakriyavatthuvasen eva pavattati",
    "<20 idaṃ aṭṭhavidhaṃ cittaṃ kāmāvacarasaññitaṃ dasapuññakriyavatthuvasen eva pavattanti",
    "<20 idaṃ aṭṭhavidhaṃ cittaṃ kāmāvacarasaññitaṃ dasapuññakriyāvatthuvasen eva pavattati",
    "<20 idaṃ aṭṭhavidhaṃ cittaṃ kāmāvacarasaññitaṃ dasapuññakiriyavatthuvasen eva pavattati",
    "<20 idaṃ aṭṭhavidhaṃ cittaṃ kāmāvacarasaññitaṃ dasapuññakriyāvatthuvasen eva pavattati",
    "<20 idaṃ aṭṭhavidhaṃ cittaṃ kāmāvacarasaññitaṃ dasapuññakriyāvatthuvasen eva pavattati",
    "<20 idaṃ aṭṭhavidhaṃ cittaṃ kāmāvacarasaññitaṃ dasapuññakriyavatthuvasen eva pavattati",
    "<20 idaṃ aṭṭhavidhaṃ cittaṃ kāmāvacarasaññitaṃ dasapuññakriyavatthuvasen eva pavattati",
    "<20 idaṃ aṭṭhavidhaṃ cittaṃ kāmāvacarasaññitaṃ dasapuññakriyavatthuvasen eva pavattati",
  ],
  ["", "", "", "", "", "", "", "", "", "", "", "", ""],
];
