var editionIds = [
  "CS",
  "PTS",
  "G",
  "A",
  "B",
  "I",
  "C",
  "D",
  "E",
  "F",
  "H",
  "K",
];

var bibleEditions = [
  "CS",
  "PTS",
  "G",
  "A",
  "B",
  "I",
  "C",
  "D",
  "E",
  "F",
  "H",
  "K",
];

var verses = "1 - 10";

var bibleVerses = [
  [
    "<1> anantakaruṇāpaññaṃ tathāgatamanuttaraṃ vanditvā sirasā buddhaṃ dhammaṃ sādhugaṇam pi ca",
    "<1> anantakaruṇāpaññaṃ tathāgatam anuttaraṃ vanditvā sirasā buddhaṃ dhammaṃ sādhugaṇam pi ca",
    "<1> anantakaruṇāpaññaṃ tathāgatam anuttaraṃ vanditvā sirasā buddhaṃ dhammaṃ sādhugaṇam pi ca",
    "<1> anantakaruṇāpaññaṃ Tathagatam anuttaraṃ vanditvā sirasā buddhaṃ dhammaṃ sādhugaṇaṃ pi ca",
    "<1> anantakaruṇaṃ paññaṃ tathāgatam anuttamaṃ vanditvā sīrasā buddhaṃ dhammasādhugaṇam pi ca",
    "<1> anantakaruṇāpaññaṃ tathāgatam anuttaraṃ vanditvā sīrasā buddhaṃ dhammaṃ sādhugaṇam pi ca",
    "<1> anantakaruṇāsaññaṃ tathagatam anuttaraṃ vanditvā sīrasā buddhaṃ dhammaṃ sadhugaṇaṃ pi ca",
    "<1> anantakaruṇāpaññaṃ tathāgatam anuttamaṃ vanditvā sīrasā buddhaṃ dhammaṃ sādhugaṇam pi ca",
    "<1> anantakaruṇāpaññaṃ tathāgatam anuttaraṃ vanditvā sirasā buddhaṃ dhammaṃ sādhugaṇam pi ca",
    "<1> anantakaruṇāpaññaṃ tathāgatam anuttamaṃ vanditvā sīrasā buddhaṃ dhammaṃ sādhugaṇam pi ca",
    "<1> anantakaruṇāpaññaṃ tathāgatam anuttaraṃ anuttamaṃ vanditvā sirasā buddhaṃ dhammaṃ sādhugaṇam pi ca",
    "<1> anantakaruṇāpaññaṃ tathāgatam anuttamaṃ vanditvā sīrasā buddhaṃ dhammaṃ sādhugaṇam pi ca",
  ],
  [
    "<2> paṇḍukambalanāmāya silāyātulavikkamo nisinno devarājassa vimale sītale tale",
    "<2> paṇḍukambalanāmāya silāyātulavikkamo nisinno devarājassa vimale sītale tale",
    "<2> paṇḍukambalanāmāya silāyātulavikkamo nisinno devarājassa vimale sītale tale",
    "<2> paṇḍukambalanāmāya silāyātulavikkamo nisinno devarājassa vimale sītale tale",
    "<2> maṇḍukampalanādhāya sīlāyatulavikkamo nisinno devarājassa vimale sitale le",
    "<2> paṇḍukambalanāmāya sīlāyatulavikkamo nisinno devarājassa vimale sītale tale",
    "<2> paṇḍukampalanāmāya sīlāyatulavikkamo nisinno devarājassa vimale sītale tale",
    "<2> paṇḍukappalanāmāya salāyāthulavikkamo nisinno devarājassa vimale sitale tale",
    "<2> paṇḍukampalanāmāya silāyatulavikkamo nisinno devarājassa vimale sitale tale",
    "<2> paṇḍukambalanāmāya sīlāyatulavikkamo nisinno devarājassa vimale sītale tale",
    "<2> paṇḍukambalanāmāya silāyātulavikkamo nisinno devarājassa vimale sītale tale",
    "<2> paṇḍukambalanāmāya sīlāyatulavikkamo nisinno devarājassa vimale sitale tale",
  ],
  [
    "<3> yaṃ devadevo devānaṃ devadevehi pūjito desesi devalokasmiṃ dhammaṃ devapurakkhato",
    "<3> yaṃ devadevo devānaṃ devadevehi pūjito desesi devalokasmiṃ dhammaṃ devapurakkhato",
    "<3> yaṃ devadevo devānaṃ devadevehi pūjito desesi devalokasmiṃ dhammaṃ devapurakkhito",
    "<3> yaṃ devadevo devānaṃ devadevehi pūjito desesi devalokasmiṃ dhammaṃ devapurakkhato",
    "<3> yaṃ devadevo devānaṃ devadevehi pūjito deseti devalokasmiṃ dhammaṃ devapūrakkhito",
    "<3> yaṃ devadevo devānaṃ devadevehi pūjito desesi devalokasmiṃ dhammaṃ devapurakkhato",
    "<3> yaṃ devadevo devānaṃ devadevehi pūjito deseti devalokasmiṃ dhammaṃ devapurakkhato",
    "<3> yaṃ devadevo devānaṃ devadevehi pūjito desesi devalokasmiṃ dhammaṃ devapurakkhato",
    "<3> yaṃ devadevo devānaṃ devadevehi pūjito desesi devalokasmiṃ dhammaṃ devapurakkhito",
    "<3> yaṃ devadevo devānaṃ devadevehi pūjito desesi devalokasmiṃ dhammaṃ devapūrakkhito",
    "<3> yaṃ devadevo devānaṃ devadevehi pūjito desesi devalokasmiṃ dhammaṃ devapurakkhato",
    "<3> yaṃ devadovo devānaṃ devadevehi pūjito desesi devalokasmiṃ dhammaṃ devapurakkhato",
  ],
  [
    "<4> tatthāhaṃ pāṭavatthāya bhikkhūnaṃ piṭakuttame abhidhammāvatāran tu madhuraṃ mativaḍḍhanaṃ ",
    "<4> tatthāhaṃ pāṭavatthāya bhikkhūnaṃ piṭakuttame abhidhammāvatāran tu madhuraṃ mativaḍḍhanaṃ",
    "<4> tatthāhaṃ pāṭavatthāya bhikkhūnaṃ piṭakuttame abhidhammāvatāran tu madhuraṃ mativaḍḍhanaṃ",
    "<4> tattha taṃ pāṭavatthāya bhikkhūnaṃ piṭakuttame abhidhammāvatāran tu madhuraṃ mativaḍḍhanaṃ",
    "<4> tatthā taṃ pāṭavatthāya bhikkhūnaṃ piṭakuttame abhidhammāvatāran tu madhuraṃ mativaḍḍhanaṃ",
    "<4> tatthāhaṃ pāṭavatthāya bhikkhūnaṃ piṭakuttame abhidhammāvatāran tu madhuraṃ mativaḍḍhanaṃ",
    "<4> tatthā taṃ pāṭavatthāya bhikkhunaṃ piṭakuttame abhidhammāvatāran tu madhūram ativaḍḍhanaṃ",
    "<4> tatthāhaṃ pāṭavatthāya bhikkhūnaṃ piṭakuttame abhidhammāvatārantu madhuraṃ mativaḍḍhanaṃ ",
    "<4> tatthā yaṃ pāṭavattāya bhikkhūnaṃ piṭakuttame abhidhammāvatāran tu madhuraṃ mativaḍḍhanaṃ",
    "<4> tatthāhaṃ pāṭavatthāya bhikkhūnaṃ piṭakuttame abhidhammāvatāran tu madhuraṃ mativaḍḍhanaṃ",
    "<4> tatthāhaṃ pāṭavatthāya bhikkhūnaṃ piṭakuttame abhidhammāvatāran tu madhuraṃ mativaḍḍhanaṃ",
    "<4> tatthāhaṃ pāṭavatthāya bhikkhūnaṃ piṭakuttame abhidhammāvatāran tu madhuraṃ mativaḍḍhanaṃ",
  ],
  [
    "<5> tāḷaṃ mohakavāṭassa vighāṭanam anuttaraṃ bhikkhūnaṃ pavisantānaṃ abhidhammamahāpuraṃ",
    "<5> tāḷaṃ mohakavāṭassa vighāṭanam anuttaraṃ bhikkhūnaṃ pavisantānaṃ abhidhammamahāpuraṃ",
    "<5> tāḷaṃ mohakavāṭassa vighāṭanam anuttaraṃ bhikkhūnaṃ pavisantānaṃ abhidhammamahāpuraṃ",
    "<5> tāḷaṃ motakavāṭassa vighāṭanam anūttaraṃ bhikkhūnaṃ pavisantānaṃ abhidhammamahāpuraṃ",
    "<5> tāḷaṃ mohakavāṭassa vighāḷana anuttara bhikkhūnaṃ pavisantānaṃ abhidhammamahāpuraṃ",
    "<5> tāḷaṃ mohakavāṭassa vighaṭanam anuttaraṃ bhikkhūnaṃ pavisantānaṃ abhidhammamahāpuraṃ",
    "<5> tāḷa mohakavātassa vighaṭanam anuttaraṃ bhikkhunaṃ pavisantānaṃ abhidhammāmahāpūraṃ",
    "<5> tāḷaṃ mohakavātassa vighāṭanam anuttaraṃ bhikkhūnaṃ pavisantānaṃ abhidhammamahāpuraṃ",
    "<5> tālaṃ mohakavāṭassa vaghāṭanam anuttaraṃ bhikkhunaṃ pavisantanaṃ abhidhammamahāpuraṃ",
    "<5> tāḷaṃ mohakavāṭassa vighāṭanam anuttaraṃ bhikkhūnaṃ pavisantānaṃ abhidhammamahāpuraṃ",
    "<5> tāḷaṃ mohakavāṭassa vighāṭanam anuttaraṃ bhikkhūnaṃ pavisantānaṃ abhidhamma-mahāpuraṃ",
    "<5> tāḷaṃ mohakavāṭassa vighāṭanam anuttaraṃ bhikkhūnaṃ pavisantānaṃ abhidhammamahāpuraṃ",
  ],
  [
    "<6> suduttaraṃ tarantānaṃ abhidhammamahodadhiṃ suduttaraṃ tarantānaṃ taraṃ va makarākaraṃ",
    "<6> suduttaraṃ tarantānaṃ abhidhammamahodadhiṃ suduttaraṃ tarantānaṃ taraṃ va makarākaraṃ",
    "<6> suduttaraṃ tarantānaṃ abhidhammamahodadhiṃ suduttaraṃ tarantānaṃ taraṃ va maṃkarākaraṃ",
    "<6> suduttaraṃ tarantānaṃ abhidhammamahodadhiṃ suduttaraṃ tarantānaṃ taraṃ va makarākaraṃ",
    "<6> suduttaraṃ bharantānaṃ abhidhammamahodadha suduttaraṃ tarantānaṃ taraṃ ca makarākaraṃ",
    "<6> suduttaraṃ tarantānaṃ abhidhammamahodadhiṃ suduttaraṃ tarantānaṃ taraṃ ca pakarākaraṃ",
    "<6> suduttaraṃ tarantānaṃ abhidhammamatodadhi suduttaraṃ tarantānaṃ taraṃ va makarākaraṃ",
    "<6> suduttaraṃ parantānaṃ abhidhammamahodadhi suduttaraṃ tarantānaṃ taraṃ va makarākaraṃ",
    "<6> suduttaraṃ tarantānaṃ abhidhammamahodadhi suduttaraṃ tarantānaṃ taraṃ va makarākaraṃ",
    "<6> suduttaraṃ tarantānaṃ abhidhammamahodadhiṃ suduttaraṃ tarantānaṃ taraṃ va makarākaraṃ",
    "<6> suduttaraṃ tarantānaṃ abhidhammamahodadhiṃ suduttaraṃ tarantānaṃ taraṃ va makarākaraṃ makarīkaraṃ",
    "<6> suduttaraṃ tarantānaṃ abhidhammamahodadhiṃ suduttaraṃ tarantānaṃ taraṃ va makarākaraṃ",
  ],
  [
    "<7> ābhidhammikabhikkhūnaṃ hatthasāram anuttaraṃ pavakkhāmi samāsena taṃ suṇātha samāhitā",
    "<7> ābhidhammikabhikkhūnaṃ hatthasāram anuttaraṃ pavakkhāmi samāsena taṃ suṇātha samāhitā",
    "<7> ābhidhammikabhikkhūnaṃ hatthasāram anuttaraṃ pavakkhāmi samāsene taṃ suṇātha samāhitā",
    "<7> ābhidhammikabhikkhūnaṃ hatthasāram anuttaraṃ pavakkhāma samāsena taṃ suṇātha samāhitā",
    "<7> abhidhammikabhikkhunaṃ hatthasāram anuttaraṃ pavakkhāmi samāsena taṃ suṇātha samāhitā",
    "<7> abhidhammikabhikkhūnaṃ hatthasāram anuttaraṃ pavakkhāmi samāsena taṃ suṇātha samāhitā",
    "<7> abhidhammikabhikkhunaṃ hatthasāram anuttaraṃ pavakkhami samāsena taṃ suṇātha samāhitā",
    "<7> abhidhammikabhikkhūnaṃ hatthasāram anuttaraṃ pavakkhāmi samāsena taṃ suṇātha samāhitā",
    "<7> abhidhammikabhikkūnaṃ hattasāram anuttaraṃ pavakkhāmi samāsema taṃ suṇātha samāhitā",
    "<7> abhidhammikabhikkhūnaṃ hatthasāram anuttaraṃ pavakkhāmi samāsena taṃ suṇātha samāhitā",
    "<7> ābhidhammikabhikkhūnaṃ hatthasāram anuttaraṃ pavakkhāmi samāsena taṃ suṇātha samāhitā",
    "<7> abhidhammikabhikkhūnaṃ hatthasāram anuttaraṃ pavakkhāmi samāsena taṃ suṇātha samāhitā",
  ],
  [
    "<8> cittaṃ cetasikaṃ rūpaṃ nibbānan ti niruttaro catudhā desayī dhamme catusaccappakāsano tattha cittan ti visayavijānanaṃ cittaṃ tassa pana ko vacanattho vuccate sabbasaṅgāhakavasena pana cintetī ti cittaṃ attasantānaṃ vā cinotī ti pi cittaṃ ",
    "<8> cittaṃ cetasikaṃ rūpaṃ nibbānan ti niruttaro catudhā desayī dhamme catusaccappakāsano tattha cittan ti visayavijānanaṃ cittaṃ tassa pana ko vacanattho vuccate sabbasaṅgāhakavasena pana cintetī ti cittaṃ attasantānaṃ vā cinotī ti pi cittaṃ ",
    "<8> citta cetasika rūpa nibbānan ti naruttaro catudhā desayī dhamme catusaccappakāsano ti tattha cittan ti visayavijānanaṃ cittaṃ tassa pana ko vacanattho vuccate sabbasaṅgāhikavasena pana cintetī ti cittaṃ attano santānaṃ vā cinotī ti vā cittaṃ ",
    "<8> cittaṃ cetasikaṃ rūpaṃ nibbānan ti niruttaro catudhā desayī dhamme catusaccappakāsano tattha cittan ti visayavijānanaṃ cittaṃ tassa pana ko vacanatthā vuccate sabbasaṅgāhakavasena pana cintetī ti cittaṃ attasantānaṃ vā cinotī ti pi cittaṃ ",
    "<8> cittacetasikaṃ rūpaṃ nibbānan ti ti niruttaro catudhā desayi dhamme catusaccappakāsano tattha cittan ti vijiyavijānanaṃ cittaṃ tassa pana ko vacanattho vuccate sabbasaṅgāhikavanesa vana cintetī ti cittaṃ attano santānaṃ vā cinotī ti pi cittaṃ",
    "<8> cittaṃ cetasikaṃ rūpaṃ nibbānan ti niruttaro catudhā desayī dhamme catusaccappakāsano tattha cittan ti visayavijānanaṃ cittaṃ tassa pana to vacanattho vuccate sabbasaṅgāhakavasena pana cintetī ti cittaṃ attano santānaṃ vā cinotī ti pi cittaṃ ",
    "<8> cittaṃ cetasikaṃ rūpaṃ nibbānan ti niruttaro catudhā desayi dhamme catusaccapakāsano tattha cittan ti visayavijānanaṃ cittaṃ tassa pana ko vacanattho vuccate sabbasaṅgahakavasena pana cintetī ti cittaṃ attano santānaṃ panotī ti cittaṃ",
    "<8> cittaṃ cetasikaṃ rūpaṃ nibbānan ti niruttaro catudhā desayi dhamme catusaccappakāsano tattha cittan ti visayavijānana cittaṃ tassa pana ko vacanattho vuccate sabbasaṃāhakavasena cintetī ti cittaṃ attano santānaṃ vā cinotī ti pi cittaṃ",
    "<8> cittaṃ cetasikaṃ rūpaṃ nibbānan ti niruttaro catudhā desayi dhamme catusaccappakāsano tattha cittan ti visayavijānanaṃ cittaṃ tassa pana ko vacanattho vuccate sabbasaṅgāhikavasena pana cintetī ti cittaṃ attano santānaṃ vā cinotī ti pi cittaṃ",
    "<8> cittaṃ cetasikaṃ rūpaṃ nibbānan ti niruttaro catudhā desayī dhamme catusaccappakāsano tattha cittan ti visayavijānanaṃ cittaṃ tassa pana ko vacanattho vuccate sabbasaṃgāhakavasena cintetī ti cittaṃ attano santānaṃ vā cinotī ti pi cittaṃ ",
    "<8> cittaṃ cetasikaṃ rūpaṃ nibbānan ti niruttaro catudhā desayī dhamme catusaccappakāsano tattha cittan ti visayavijānanaṃ cittaṃ tassa pana ko vacanattho vuccate sabbasaṅgāhakavasena pana cintetī ti cittaṃ attasantānaṃ vā cinotī ti pi cittaṃ ",
    "<8> cittaṃ cetasikaṃ rūpaṃ nibbānan ti niruttaro catu desayī dhamme catusaccappakāsano tattha cittan ti visayavijānanaṃ cittaṃ tassa pana ko vacanattho vuccate sabbasaṃgāhakavasena cintetī ti cittaṃ attano santānaṃ vā cinotī ti pi cittaṃ ",
  ],
  [
    "<9> vicittakaraṇā cittaṃ attano cittatāya vā paññattiyam pi viññāṇe vicitte cittakammake cittasammuti daṭṭhabbā viññāṇe idha viññunā taṃ pana sārammaṇato ekavidhaṃ savipākāvipākato duvidhaṃ tattha savipākaṃ nāma kusalākusalaṃ avipākaṃ abyākataṃ kusalākusalābyākatajātibhedato tividhaṃ tattha kusalan ti pan etassa ko vacanattho",
    "<9> vicittakaraṇā cittaṃ attano cittatāya vā; paññattiyam pi viññāṇe vicitte cittakammake cittasammuti daṭṭhabbā viññāṇe idha viññunā taṃ pana sārammaṇato ekavidhaṃ savipākāvipākato duvidhaṃ tattha savipākaṃ nāma kusalākusalaṃ; avipākaṃ abyākataṃ kusalākusalābyākatajātibhedato tividhaṃ; tattha kusalan ti pan etassa ko vacanattho",
    "<9> vicittakaraṇā cittaṃ attano cittatāya vā; paññattiyam pi viññāṇe vicitte cittakammake cittasammuti daṭṭhabbā viññāṇe idha viññunā taṃ pana sārammaṇato ekavidhaṃ savipākāvipākato duvidhaṃ tattha savipākaṃ nāma kusalākusalaṃ; avipākaṃ abyākataṃ kusalākusalābyākatajātibhedato tividhaṃ; tattha kusalan ti pan etassa ko vacanattho",
    "<9> vicittakaraṇā cittaṃ attano cittatāya vā; paññattiyam pi viññāṇe vicitte cittakammake cittasammuti daṭṭhabbā viññāṇe idha viññunā taṃ pana sārammaṇato ekavidhaṃ savipākāvipākato duvidhaṃ tattha savipākaṃ nāma kusalākusalaṃ; avipākam abyākataṃ kusalākusalābyākatajātibhedato tividhaṃ; tattha kusalan ti pan etassa ko vacanattho",
    "<9> vicittakaraṇā cittaṃ attano cittatāya vā; paññattiyaṃ pi viññāṇe vicitte cittikammake cittasammuti daṭṭhabbā viññāṇe idha viññunā taṃ pana sārammaṇato ekavidhaṃ savipākāvipākato duvidhaṃ tattha savipākaṃ nāma kusalākusalaṃ; avipākam abyākataṃ kusalākusalābyākatajātibhedato tividhaṃ; tattha kusalan ti pan etassa ko vacanattho",
    "<9> vicittakaraṇā cittaṃ attano cittatāya vā; paññattiyam pi viññāṇe vicitthe cittakammake cittasammuti daṭṭhabbā viññāṇe idha viññunā taṃ pana sārammaṇako ekavidhaṃ savipākāvipākato duvidhaṃ tattha savipākaṃ nāma kusalākusalaṃ; avipākam abyākataṃ kusalākusalābyākatajātibhedato tividhaṃ; tattha kusalan ti pan etassa ko vacanattho",
    "<9> vicittakaraṇā cittaṃ attano cittathāya vā; paññattiyam pi viññāṇe vicitte cittakammake cittasammuti daṭṭhabbā viññāṇe idha viññunā tham pana sārammaṇato ekavidhaṃ savipākāvipākato duvidhaṃ tattha savipākaṃ nāma kusalākusalaṃ; avipākam abyākathaṃ kusalākusalābyākatajātibhedato tividhaṃ; tattha kusalan ti pan etassa ko vacanattho",
    "<9> vicittakaraṇā cittaṃ attano cittatāya vā; paññattiyam pi viññāṇe vicitte cittakammake cittasammuti daṭṭhabbā viññāṇe idha viññunā taṃ pana sārammaṇato ekavidhaṃ savipākāvipākato duvidhaṃ tattha savipākaṃ nāma kusalākusalaṃ; avipākam abyākataṃ kusalākusalābyākatajātibhedato tividhaṃ; tattha kusalan ti pan etassa ko vacanattho",
    "<9> vicittakaraṇā cittaṃ attano cittatāya vā; paññattiyam pi viññāṇe vicitte cittikammake cittasammuti daṭṭhabbā viññāṇe idha viññunā taṃ pana sārammaṇato ekavidhaṃ savipākāvipākato duvidhaṃ tattha savipākaṃ nāma kusalākusalaṃ; avipākam abyākataṃ kusalākusalābyākatajātibhedato tividhaṃ; tattha kusalan ti pan etassa ko vacanattho",
    "<9> vicittakaraṇā cittaṃ attano cittatāya vā; paññattiyam pi viññāṇe vicitte cittakammake cittasamuti daṭṭhabbā viññāṇe idha viññunā taṃ pana sārammaṇato ekavidhaṃ savipākāvipākato duvidhaṃ tattha savipākaṃ nāma kusalākusalaṃ; avipākam abyākataṃ kusalākusalābyākatajātibhedato tividhaṃ; tattha kusalan ti pan etassa ko vacanattho",
    "<9> vicittakaraṇā cittaṃ attano cittatāya vā; paññattiyam pi viññāṇe vicitte cittakammake cittasammuti daṭṭhabbā viññāṇe idha viññunā taṃ pana sārammaṇato ekavidhaṃ savipākāvipākato duvidhaṃ tattha savipākaṃ nāma kusalākusalaṃ; avipākam abyākataṃ kusalākusalābyākatajātibhedato tividhaṃ; tattha kusalan ti pan etassa ko vacanattho",
    "<9> vicittakaraṇā cittaṃ attano cittatāya vā; paññattiyam pi viññāṇe vicitte cittakammake cittasammuti daṭṭhabbo viññāṇe idha viññunā taṃ pana sārammaṇato ekavidhaṃ savipākāvipākato duvidhaṃ tattha savipākaṃ nāma kusalākusalaṃ; avipākaṃ abyākataṃ kusalākusalābyākatajātibhedato tividhaṃ; tattha kusalan ti pan etassa ko vacanattho",
  ],
  [
    "<10 kucchitānaṃ salanato kusānaṃ lavanena vā kusena lātabbattā vā kusalan ti pavuccati",
    "<10 kucchitānaṃ salanato kusānaṃ lavanena vā kusena lātabbattā vā kusalan ti pavuccati",
    "<10 kucchitānaṃ sasanato kusānaṃ lavanena vā kusena lātabbattā vā kusalan ti pavuccati",
    "<10 kucchitānaṃ salanato kusānaṃ lavanena vā kusena lātabbattā vā kusalan ti pavuccati",
    "<10 kucchitānaṃ salanato kusānaṃ lavanena vā kusena lātabbattā vā kusalan ti pavuccati",
    "<10 kucchitānaṃ salanato kusānaṃ lavanena vā kusena lātabbattā vā kusalan ti pavuccati",
    "<10 kucchithānaṃ salanato kusānaṃ lavanena vā kusena lātabbattā vā kusalan ti pavuccati",
    "<10 kucchitānaṃ salanato kusānaṃ lavanena vā kusena lātabbattā vā kusalan ti pavuccati",
    "<10 kucchitānaṃ salanato kusānaṃ lavanena vā kusena lātabbattā vā kusalan ti pavuccati",
    "<10 kucchitānaṃ salanato kusānaṃ lavanena vā kusena lātabbatthā vā kusalan ti pavuccati",
    "<10 kucchitānaṃ salanato kusānaṃ lavanena vā kusena lātabbattā vā kusalan ti pavuccati",
    "<10 kucchitānaṃ salanato kusānaṃ lavanena vā kusena lātabbatthā vā kusalan ti pavuccati",
  ],
  ["", "", "", "", "", "", "", "", "", "", "", "", ""],
];
